### ISSUE TITLE
Implement a validator for different trust domains and root certificates

### ISSUE THREAD

**Issue by yxun** [openshift-service-mesh/federation#25]
A mesh trust domain can be set from an Istio `meshConfig.trustDomain` field or SMCP `spec.security.trust.domain`
When connecting meshes in federation, each mesh must have its own unique trust domain.
- Need a validator for checking each mesh trust domain is unique.

- Need a validator for checking a resource e.g. ConfigMap containing the root certificate used to validate the client and server certs. The root certificate should be presented to one mesh by the peer mesh. 
- (Optional) Check the root certificates are not expired.

**Comment by jewertow** [comment]
We do not need this validation, because currently, we only support common trust domain and root certificate. To support different roots and trust domain, we must implement proper certificate validator in Istio, but this requires an RFC first. But even if we will support different roots and trust domains, the federation controller will not be responsible for validating Istio control plane configuration and certs. Such validations could be done by the operator (maybe sail) or ACM (if it will support federation).
